import type { Metadata } from "next";
import "./globals.css";
import Header from './components/Header'
import Footer from './components/Footer'
import ComingSoon from "./components/ComingSoon";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const isProduction = process.env.NEXT_PUBLIC_ENV === "production";

  return (
    <html lang="en">
      <body
        className=" antialiased"
        cz-shortcut-listen="true"
      >
        <div className="">

       {isProduction ?
        <ComingSoon /> 
        : 
        <>
          <Header/>
          {children}
          <Footer/>
        </>
        }

       
        </div>
      </body>
    </html>
  );
}
