import type { Metadata } from "next";
import { headers } from "next/headers";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import ComingSoon from "./components/ComingSoon";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout artık async
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // headers() Promise döndüğü için await kullanıyoruz
  const hdrs = await headers();
  const host = hdrs.get("host") || "";

  const isProd = process.env.NEXT_PUBLIC_ENV === "production";

  // sadece preview domaininde ve production değilken
  const isPreviewHost = host === "swissdental.vercel.app";
  const showComingSoon = !isProd && isPreviewHost;

  return (
    <html lang="en">
      <body className="antialiased">
        {showComingSoon ? (
          <ComingSoon />
        ) : (
          <>
            <Header />
            {children}
            <Footer />
          </>
        )}
      </body>
    </html>
  );
}
